# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Check code style"
  lane :lint_code do 
    swiftlint(
      mode: :lint,
      config_file: "./.swiftlint.yml"
    )
  end

  desc "Clear XCov output folder"
  lane :clear_xcov_report do
    sh "cd .. && if [ -d 'code-coverage-report' ]; then rm -Rf code-coverage-report; fi"
  end

  desc "Create coverage report"
  lane :coverage do 
    clear_derived_data
    clear_xcov_report
    run_tests(scheme: "unit-tests", devices: ["iPhone 14 Pro (16.4)"])
    # https://docs.fastlane.tools/actions/xcov/
    xcov(
          project: "marvel-store.xcodeproj",
          scheme: "unit-tests",
          output_directory: "code-coverage-report",
          ignore_file_path: "./.xcovignore"
        )
  end

  desc "Used by Development to keep code quality. Use command: 'fastlane check_code dev:true'"
  lane :check_code do |options|
    clear_derived_data
    lint_code
    scan(code_coverage: true)

    if options[:dev]
      coverage
    end
  end
end